services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      array $definitions: '%babymarkt_cron.definitions%'

  Babymarkt\Symfony\CronBundle\Command\:
    resource: '../../Command/'
    tags: [ { name: console.command } ]

  Babymarkt\Symfony\CronBundle\Crontab\Factory\CrontabEntryGeneratorFactory:
    arguments:
      - $definitions: '%babymarkt_cron.definitions%'
      - $outputOptions: '%babymarkt_cron.options.output%'
      - $baseDir: '%babymarkt_cron.options.working_dir%'
      - $environment: '%kernel.environment%'

  Babymarkt\Symfony\CronBundle\Crontab\CrontabEntryGenerator:
    factory: [ '@Babymarkt\Symfony\CronBundle\Crontab\Factory\CrontabEntryGeneratorFactory', create ]
    calls:
      - [ setScript, [ '%babymarkt_cron.options.script%' ] ]

  Babymarkt\Symfony\CronBundle\Crontab\Writer\CrontabWriterInterface:
    class: Babymarkt\Symfony\CronBundle\Crontab\Writer\CrontabWriter
    arguments:
      - $config: '%babymarkt_cron.options.crontab%'

  Babymarkt\Symfony\CronBundle\Crontab\Reader\CrontabReaderInterface:
    class: Babymarkt\Symfony\CronBundle\Crontab\Reader\CrontabReader
    arguments:
      - $config: '%babymarkt_cron.options.crontab%'

  Babymarkt\Symfony\CronBundle\Crontab\CrontabEditor:
    arguments:
      - $identifier: '%babymarkt_cron.options.id%'

  Babymarkt\Symfony\CronBundle\Shell\ShellWrapperInterface:
    class: Babymarkt\Symfony\CronBundle\Shell\ShellWrapper

  Babymarkt\Symfony\CronBundle\Crontab\DefinitionChecker: ~


