name: Build

on:
  push:
    branches: [ 2.x ]
  pull_request:
    branches: [ 2.x ]

jobs:
  build_and_test:
    name: Test with php ${{ matrix.php_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: ['7.4', '8.0', '8.1', '8.2']

    steps:
    - uses: actions/checkout@v2

    # https://github.com/marketplace/actions/setup-php-action
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php_version }}
        coverage: xdebug

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run PHPUnit
      run: vendor/bin/phpunit --coverage-clover=coverage.xml
      env:
        ENABLE_SECOND_LEVEL_CACHE: 0

    - name: Upload coverage file
      uses: actions/upload-artifact@v2
      with:
        name: phpunit-php${{ matrix.php_version }}-coverage
        path: coverage*.xml

  upload_coverage:
    name: Upload coverage to Codecov
    runs-on: ubuntu-latest
    needs:
      - build_and_test

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Download coverage files
        uses: actions/download-artifact@v2
        with:
          path: reports

      - name: Upload to Codecov
        uses: codecov/codecov-action@v2.1.0
        with:
          directory: reports
